language: node_js
node_js:
  - "lts/8"
cache:
  directories:
    - "backend/node_modules"
    - "frontend/node_modules"
before_install:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
  # install packages
  - cd frontend && yarn install
  - cd backend && yarn install
script:
  - cd backend && npm test
