language: node_js
node_js:
  - "8"
cache:
  directories:
    - "backend/node_modules"
    - "frontend/node_modules"
before_install:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
  # install packages
  - cd frontend && yarn install && cd ..
  - cd backend && npm install && cd ..
  # install certs
  - cd backend && curl https://github.com/kristophjunge/docker-test-saml-idp/blob/master/config/simplesamlphp/server.crt > keys/idp_cert.pem && cd ..
script:
  - cd backend && npm test && cd ..
