language: node_js
node_js:
  - "8"
services:
  - mysql
env:
  - ABSTRACTION_DB_USER=travis
  - ABSTRACTION_DB_PASS=
  - ABSTRACTION_DB_HOST=localhost
cache:
  directories:
    - "backend/node_modules"
    - "frontend/node_modules"
before_install:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
  # install packages
  - cd frontend && yarn install && cd ..
  - cd backend && npm install && cd ..
  # install certs
  - cd backend && mkdir keys && cd ..
  - cd backend && curl https://github.com/kristophjunge/docker-test-saml-idp/blob/master/config/simplesamlphp/server.crt > keys/idp_cert.pem && cd ..
  - cd backend && npm run keygen && cd ..
  # create mysql database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - cd backend && npm test && cd ..
